## What does validation_curve returns

`validation_curve()` returns **two arrays**:

```python
train_scores, validation_scores = validation_curve(...)
```

### Shape of the returned arrays

If:

```python
param_range = [1, 2, 3, 5]
cv = 5
```

then:

```python
train_scores.shape
# (4, 5)

validation_scores.shape
# (4, 5)
```

Why `(4, 5)`?

* 4 parameter values (`1, 2, 3, 5`)
* 5 cross-validation folds

Each row corresponds to a parameter value, and each column corresponds to a CV fold.

---

### Example

```python
train_scores, val_scores = validation_curve(
    DecisionTreeClassifier(),
    X,
    y,
    param_name="max_depth",
    param_range=[1, 2, 3],
    cv=3
)

print(train_scores)
```

Output might look like:

```python
[[0.70 0.72 0.71]
 [0.85 0.84 0.86]
 [0.98 0.97 0.99]]
```

Meaning:

| max_depth | Fold 1 | Fold 2 | Fold 3 |
| --------- | ------ | ------ | ------ |
| 1         | 0.70   | 0.72   | 0.71   |
| 2         | 0.85   | 0.84   | 0.86   |
| 3         | 0.98   | 0.97   | 0.99   |

The same structure applies to `val_scores`.

---

### Usually you take the mean

```python
import numpy as np

train_mean = np.mean(train_scores, axis=1)
val_mean = np.mean(val_scores, axis=1)

print(train_mean)
print(val_mean)
```

Example output:

```python
train_mean = [0.71, 0.85, 0.98]
val_mean   = [0.69, 0.83, 0.88]
```

Now you can plot:

```python
plt.plot(param_range, train_mean, label="Training")
plt.plot(param_range, val_mean, label="Validation")
plt.legend()
```

This is exactly how validation curves are typically visualized.

### Summary

```python
train_scores, val_scores = validation_curve(...)
```

returns:

* `train_scores`: training score for every `(parameter value, CV fold)`
* `val_scores`: validation score for every `(parameter value, CV fold)`

To find the best parameter value, you usually compute:

```python
val_scores.mean(axis=1)
```

and choose the parameter with the highest average validation score.


----

----

## What does validation_curve returns

`learning_curve()` returns **three things**:

```python
train_sizes, train_scores, val_scores = learning_curve(...)
```

### 1. `train_sizes`

The actual number of training examples used for each point on the curve.

Example:

```python
train_sizes
# array([100, 300, 500, 700, 1000])
```

These are the dataset sizes on which the model was trained.

---

### 2. `train_scores`

Training scores for each training size and each CV fold.

Example with:

```python
cv = 3
train_sizes = [100, 300, 500]
```

Shape:

```python
train_scores.shape
# (3, 3)
```

Possible values:

```python
[[1.00, 1.00, 1.00],    # trained on 100 samples
 [0.95, 0.96, 0.94],    # trained on 300 samples
 [0.92, 0.91, 0.93]]    # trained on 500 samples
```

Rows = training sizes

Columns = CV folds

---

### 3. `val_scores`

Validation (cross-validation) scores for each training size and fold.

```python
val_scores
```

might be:

```python
[[0.70, 0.72, 0.69],
 [0.82, 0.81, 0.83],
 [0.88, 0.87, 0.89]]
```

Again:

* Rows = training sizes
* Columns = folds

---

### Typical usage

```python
import numpy as np

train_mean = train_scores.mean(axis=1)
val_mean = val_scores.mean(axis=1)
```

Result:

| Training Size | Train Score | Validation Score |
| ------------- | ----------- | ---------------- |
| 100           | 1.00        | 0.70             |
| 300           | 0.95        | 0.82             |
| 500           | 0.92        | 0.88             |

This table is what you usually plot.

---

### Comparison with `validation_curve`

| Function             | Returns                                   |
| -------------------- | ----------------------------------------- |
| `learning_curve()`   | `(train_sizes, train_scores, val_scores)` |
| `validation_curve()` | `(train_scores, val_scores)`              |

The extra output is `train_sizes`, because a learning curve varies the **amount of training data**, while a validation curve varies a **hyperparameter** whose values you already know from `param_range`.
