In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
#sharper plots
%config InlineBackend.figure_format = 'retina'
from sklearn.datasets import load_files
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression


In [2]:
def load_dataset(extract_path, overwrite=False):
    if os.path.isfile(os.path.join(extract_path,"imdb-test","README")):
        print("dataset already in place")
        return
    else:
        print("dataset not found")

In [3]:
DATA_PATH = "."

load_dataset(extract_path=DATA_PATH)

dataset already in place


In [4]:
PATH_TO_IMDB_TRAIN = "./imdb-test/train"
PATH_TO_IMDB_TEST = "./imdb-test/test"

reviews_train = load_files(
    PATH_TO_IMDB_TRAIN, categories=["pos","neg"]
)

text_train, y_train = reviews_train.data, reviews_train.target

reviews_test = load_files(
    PATH_TO_IMDB_TEST, categories=["pos","neg"]
)

text_test, y_test = reviews_test.data, reviews_test.target

df = pd.DataFrame({
    "review":reviews_train.data,
    "target" : reviews_train.target
})
print(df)
print(reviews_train.keys())

                                               review  target
0   b'Bromwell High is a cartoon comedy. It ran at...       1
1   b"I came in in the middle of this film so I ha...       1
2   b"This fanciful horror flick has Vincent Price...       0
3   b"FUTZ is the only show preserved from the exp...       1
4   b'I saw the capsule comment said "great acting...       0
5   b'Bromwell High is nothing short of brilliant....       1
6   b"Robert DeNiro plays the most unbelievably in...       0
7   b"If you like adult comedy cartoons, like Sout...       1
8   b'"All the world\'s a stage and its people act...       1
9   b"If I had not read Pat Barker's 'Union Street...       0
10  b"Story of a man who has unnatural feelings fo...       0
11  b"I basically skimmed through the movie but ju...       0
dict_keys(['data', 'filenames', 'target_names', 'target', 'DESCR'])


In [5]:
text_train[1]

b"I came in in the middle of this film so I had no idea about any credits or even its title till I looked it up here, where I see that it has received a mixed reception by your commentators. I'm on the positive side regarding this film but one thing really caught my attention as I watched: the beautiful and sensitive score written in a Coplandesque Americana style. My surprise was great when I discovered the score to have been written by none other than John Williams himself. True he has written sensitive and poignant scores such as Schindler's List but one usually associates his name with such bombasticities as Star Wars. But in my opinion what Williams has written for this movie surpasses anything I've ever heard of his for tenderness, sensitivity and beauty, fully in keeping with the tender and lovely plot of the movie. And another recent score of his, for Catch Me if You Can, shows still more wit and sophistication. As to Stanley and Iris, I like education movies like How Green was

In [6]:
cv = CountVectorizer() 
cv.fit(text_train) # returns a dict of number and the words


,"input input: {'filename', 'file', 'content'}, default='content'- If `'filename'`, the sequence passed as an argument to fit is expected to be a list of filenames that need reading to fetch the raw content to analyze.- If `'file'`, the sequence items must have a 'read' method (file-like object) that is called to fetch the bytes in memory.- If `'content'`, the input is expected to be a sequence of items that can be of type string or byte.",'content'
,"encoding encoding: str, default='utf-8'If bytes or files are given to analyze, this encoding is used todecode.",'utf-8'
,"decode_error decode_error: {'strict', 'ignore', 'replace'}, default='strict'Instruction on what to do if a byte sequence is given to analyze thatcontains characters not of the given `encoding`. By default, it is'strict', meaning that a UnicodeDecodeError will be raised. Othervalues are 'ignore' and 'replace'.",'strict'
,"strip_accents strip_accents: {'ascii', 'unicode'} or callable, default=NoneRemove accents and perform other character normalizationduring the preprocessing step.'ascii' is a fast method that only works on characters that havea direct ASCII mapping.'unicode' is a slightly slower method that works on any characters.None (default) means no character normalization is performed.Both 'ascii' and 'unicode' use NFKD normalization from:func:`unicodedata.normalize`.",None
,"lowercase lowercase: bool, default=TrueConvert all characters to lowercase before tokenizing.",True
,"preprocessor preprocessor: callable, default=NoneOverride the preprocessing (strip_accents and lowercase) stage whilepreserving the tokenizing and n-grams generation steps.Only applies if ``analyzer`` is not callable.",None
,"tokenizer tokenizer: callable, default=NoneOverride the string tokenization step while preserving thepreprocessing and n-grams generation steps.Only applies if ``analyzer == 'word'``.",None
,"stop_words stop_words: {'english'}, list, default=NoneIf 'english', a built-in stop word list for English is used.There are several known issues with 'english' and you shouldconsider an alternative (see :ref:`stop_words`).If a list, that list is assumed to contain stop words, all of whichwill be removed from the resulting tokens.Only applies if ``analyzer == 'word'``.If None, no stop words will be used. In this case, setting `max_df`to a higher value, such as in the range (0.7, 1.0), can automatically detectand filter stop words based on intra corpus document frequency of terms.",None
,"token_pattern token_pattern: str or None, default=r""(?u)\\b\\w\\w+\\b""Regular expression denoting what constitutes a ""token"", only usedif ``analyzer == 'word'``. The default regexp select tokens of 2or more alphanumeric characters (punctuation is completely ignoredand always treated as a token separator).If there is a capturing group in token_pattern then thecaptured group content, not the entire match, becomes the token.At most one capturing group is permitted.",'(?u)\\b\\w\\w+\\b'
,"ngram_range ngram_range: tuple (min_n, max_n), default=(1, 1)The lower and upper boundary of the range of n-values for differentword n-grams or char n-grams to be extracted. All values of n suchsuch that min_n <= n <= max_n will be used. For example an``ngram_range`` of ``(1, 1)`` means only unigrams, ``(1, 2)`` meansunigrams and bigrams, and ``(2, 2)`` means only bigrams.Only applies if ``analyzer`` is not callable.","(1, ...)"
,"analyzer analyzer: {'word', 'char', 'char_wb'} or callable, default='word'Whether the feature should be made of word n-gram or charactern-grams.Option 'char_wb' creates character n-grams only from text insideword boundaries; n-grams at the edges of words are padded with space.If a callable is passed it is used to extract the sequence of featuresout of the raw, unprocessed input... versionchanged:: 0.21Since v0.21, if ``input`` is ``filename`` or ``file``, the data isfirst read from the file and then passed to the given callableanalyzer.",'word'


In [7]:
print(cv.get_feature_names_out()[:10])

['10' '1960s' '20' '35' 'about' 'absurd' 'accept' 'acclaim' 'accurate'
 'acting']


In [8]:
X_train = cv.transform(text_train)
X_train
X_train.nonzero()

(array([ 0,  0,  0, ..., 11, 11, 11], shape=(1247,), dtype=int32),
 array([  3,   4,  17, ..., 794, 798, 800], shape=(1247,), dtype=int32))

In [9]:
X_test = cv.transform(text_test)

In [10]:
logit = LogisticRegression(solver="lbfgs", random_state=17, max_iter=500)
logit.fit(X_train, y_train)

,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add a L2 penalty term and it is the default choice;- `'l1'`: add a L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'` and `l1_ratio` set to any float between 0 and 1 for `'penalty='elasticnet'`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation `) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary ` for details.",17
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default solver because it works reasonably well for a wide class of problems.- For :term:`multi

In [11]:
round(logit.score(X_train, y_train), 3), round(logit.score(X_test, y_test), 3),

(1.0, 0.167)

In [49]:

# coef = np.array([0.5, -2.0, 1.0, 0.2])
# np.argsort(coef) -> array([1, 3, 0, 2]) 


Not exactly. That's a very common first intuition, but logistic regression is doing something a bit smarter.

### What you're imagining

Suppose:

| Word     | Positive reviews | Negative reviews |
| -------- | ---------------- | ---------------- |
| amazing  | 20               | 1                |
| terrible | 1                | 15               |
| movie    | 30               | 28               |

A simple frequency-based method might say:

* "amazing" → positive
* "terrible" → negative
* "movie" → neutral

and assign scores based mainly on counts.

---

### What logistic regression actually learns

It tries to find weights that best separate positive and negative reviews.

Imagine these reviews:

```text
Positive:
"amazing movie"
"great movie"
"excellent acting"

Negative:
"terrible movie"
"boring movie"
"awful acting"
```

The model might learn:

| Word      | Weight |
| --------- | ------ |
| amazing   | +2.5   |
| great     | +2.1   |
| excellent | +2.4   |
| terrible  | -2.8   |
| boring    | -2.2   |
| awful     | -2.6   |
| movie     | 0.1    |
| acting    | -0.1   |

Notice that:

* "movie" appears in both classes a lot → near zero weight.
* "amazing" appears mostly in positive reviews → positive weight.
* "terrible" appears mostly in negative reviews → negative weight.

So frequency influences the result, but frequency alone is not the coefficient.

---

### A useful example

Suppose:

```text
Positive reviews:
10 contain "good"

Negative reviews:
0 contain "good"
```

and

```text
Positive reviews:
100 contain "the"

Negative reviews:
100 contain "the"
```

Even though `"the"` appears much more often, logistic regression will give:

```text
good  -> large positive weight
the   -> near zero weight
```

because `"good"` helps distinguish sentiment while `"the"` doesn't.

---

### Another important point

The weight depends on **other words too**.

For example:

```text
good movie
not good movie
```

If your features are individual words:

```text
good -> positive
not  -> negative
```

The model learns both coefficients together.

So the coefficient for `"good"` is not computed independently from counts. It's optimized together with all other coefficients to maximize classification accuracy.

---

### Mathematically

The model is finding weights (w) that make:

$$
P(\text{positive}) =
\frac{1}{1 + e^{-(w_1x_1 + w_2x_2 + \cdots + b)}}
$$

fit the training labels as well as possible.

The coefficients are found by optimization (maximum likelihood), not by counting words.

---

### In your tiny dataset (6–12 reviews)

With so little data, a word may get a huge positive or negative weight simply because it appeared in one or two reviews.

For example:

```text
Positive review:
"masterpiece"

Negative reviews:
never contain "masterpiece"
```

The model may conclude:

```text
masterpiece -> strongly positive
```

even though with more data that conclusion might disappear.

That's one reason your training accuracy is 100% and test accuracy is 16.7%: the model is learning patterns that happen to fit the few training reviews rather than patterns that generalize.


In [ ]:
coef = logit.coef_.ravel()
positive_coeff= np.argsort(coef)[-25:]
negative_coeff= np.argsort(coef)[:25]
interesting_coeff = np.hstack([negative_coeff, positive_coeff])
print(interesting_coeff)

[339  82 451  34  93 750 241 702 231  62 308  27 422 113 472 110 790 708
 273 394 252 719   5 695 447 457 435 618 800 445 561 640 323 621 417 352
 371   4  49 683 572  51 461 636 667 682 798  89 297  35]


In [56]:
feature_names = np.array(cv.get_feature_names_out())
# print(feature_names[interesting_coeff])
print(feature_names[negative_coeff])

['is' 'br' 'of' 'an' 'but' 'was' 'for' 'time' 'film' 'be' 'hot' 'all'
 'movie' 'character' 'over' 'chace' 'would' 'too' 'great' 'make' 'future'
 'turned' 'absurd' 'those' 'novel']


In [59]:
print(cv.get_feature_names_out())

['10' '1960s' '20' '35' 'about' 'absurd' 'accept' 'acclaim' 'accurate'
 'acting' 'active' 'actors' 'actually' 'adaptation' 'addition' 'adjective'
 'adult' 'adults' 'adventures' 'advise' 'advised' 'afraid' 'african'
 'after' 'age' 'aggressive' 'alas' 'all' 'almost' 'also' 'although'
 'america' 'american' 'americana' 'an' 'and' 'anger' 'angle' 'animals'
 'ann' 'annoying' 'another' 'any' 'anything' 'anyways' 'are' 'area' 'aren'
 'around' 'as' 'associates' 'at' 'attention' 'audience' 'avenging' 'avoid'
 'awakening' 'away' 'back' 'bad' 'barker' 'basically' 'be' 'beautiful'
 'beauty' 'because' 'been' 'before' 'behaved' 'being' 'believe' 'below'
 'best' 'better' 'bigger' 'bip' 'bitches' 'blunder' 'bombasticities'
 'book' 'bore' 'boring' 'br' 'briefly' 'brilliant' 'bring' 'british'
 'broadway' 'broken' 'bromwell' 'budget' 'bummer' 'burn' 'but' 'by' 'came'
 'camera' 'can' 'canada' 'capsule' 'cardboard' 'caricature' 'caricatured'
 'carolina' 'cartoon' 'cartoons' 'case' 'cast' 'catch' 'caught' 'c

---------------

Yes! You've reached the key insight behind **supervised learning**.

The model does **not** know that "good" is positive or "bad" is negative beforehand.

It learns that from the labels you provide.

### Your dataset probably looked like this

After loading the folders:

```text
positive/
    review1.txt
    review2.txt
    review3.txt

negative/
    review4.txt
    review5.txt
    review6.txt
```

you likely created something like:

| Review Text                  | Label |
| ---------------------------- | ----- |
| "good movie amazing acting"  | 1     |
| "excellent film"             | 1     |
| "terrible movie boring plot" | 0     |
| "awful acting"               | 0     |

The model sees:

```python
X_train = [
    "good movie amazing acting",
    "excellent film",
    "terrible movie boring plot",
    "awful acting"
]

y_train = [1, 1, 0, 0]
```

### After CountVectorizer

Suppose the vocabulary becomes:

```text
acting
amazing
awful
boring
excellent
film
good
movie
plot
terrible
```

Then the reviews become numbers:

| acting | amazing | awful | boring | excellent | film | good | movie | plot | terrible | Label |
| ------ | ------- | ----- | ------ | --------- | ---- | ---- | ----- | ---- | -------- | ----- |
| 1      | 1       | 0     | 0      | 0         | 0    | 1    | 1     | 0    | 0        | 1     |
| 0      | 0       | 0     | 0      | 1         | 1    | 0    | 0     | 0    | 0        | 1     |
| 0      | 0       | 0     | 1      | 0         | 0    | 0    | 1     | 1    | 1        | 0     |
| 1      | 0       | 1     | 0      | 0         | 0    | 0    | 0     | 0    | 0        | 0     |

Now Logistic Regression receives only:

```python
X = matrix_of_numbers
y = [1, 1, 0, 0]
```

No word meanings. No English knowledge.

---

### How does it discover "good" should be positive?

Initially all weights are random or zero:

```text
good      = 0
terrible  = 0
amazing   = 0
movie     = 0
...
```

The model makes predictions.

For example, for:

```text
good movie amazing acting
```

true label = 1

Suppose the model predicts:

```text
0.50
```

That's not very good.

The optimization algorithm says:

> "To make this review more likely to be class 1, increase the weights of the features present in this review."

So:

```text
good      ↑
amazing   ↑
movie     ↑
acting    ↑
```

Now look at a negative review:

```text
terrible movie boring plot
```

true label = 0

Suppose the model predicts:

```text
0.70
```

Too positive.

The optimizer says:

> "Decrease the weights of the features present here."

So:

```text
terrible  ↓
boring    ↓
plot      ↓
movie     ↓ a little
```

This process repeats hundreds of times.

---

### What happens to "movie"?

This is the interesting part.

"movie" appears in BOTH positive and negative reviews:

```text
Positive:
good movie
amazing movie

Negative:
terrible movie
boring movie
```

The optimizer notices:

> Whenever I increase the weight of "movie", it helps some positive reviews but also helps negative reviews.

So eventually:

```text
movie ≈ 0
```

because it doesn't help distinguish the classes.

---

### What happens to "good"?

Suppose:

```text
good appears in:
8 positive reviews
1 negative review
```

The optimizer discovers:

> Reviews containing "good" are usually labeled 1.

To reduce prediction errors:

```text
good = +2.3
```

---

### What happens to "bad"?

Suppose:

```text
bad appears in:
1 positive review
10 negative reviews
```

The optimizer discovers:

> Reviews containing "bad" are usually labeled 0.

So:

```text
bad = -2.8
```

---

### The crucial idea

The model is **not assigning sentiment to words directly**.

It is solving:

> "What set of weights makes the reviews with label 1 get probabilities close to 1, and reviews with label 0 get probabilities close to 0?"

The word weights emerge as a consequence of that optimization.

So yes, the fact that you labeled:

```python
positive_reviews -> 1
negative_reviews -> 0
```

is exactly how the model learns.

Without those labels, Logistic Regression would have no idea what "positive" or "negative" means.

A good mental model is:

> Logistic Regression never learns that "good" means positive.
>
> It only learns that documents containing the feature "good" tend to have the label 1 in the training data.

That's a subtle but important distinction.


---------------------

Great question. The key idea is that **the coefficients and feature names are stored in the same order**.

Let's walk through it.

### Step 1: Vectorizer creates a vocabulary

Suppose your reviews are:

```python
reviews = [
    "great movie",
    "terrible movie",
    "great acting"
]
```

After:

```python
cv = CountVectorizer()
X = cv.fit_transform(reviews)
```

you might get:

```python
cv.get_feature_names_out()
```

```python
array(['acting', 'great', 'movie', 'terrible'])
```

Notice each word has an index:

| Index | Feature  |
| ----- | -------- |
| 0     | acting   |
| 1     | great    |
| 2     | movie    |
| 3     | terrible |

---

### Step 2: Logistic regression learns one weight per feature

After training:

```python
logit.coef_
```

might be:

```python
array([[ 0.5, 2.1, 0.1, -2.8 ]])
```

which means:

| Index | Feature  | Coefficient |
| ----- | -------- | ----------- |
| 0     | acting   | 0.5         |
| 1     | great    | 2.1         |
| 2     | movie    | 0.1         |
| 3     | terrible | -2.8        |

The coefficient at position `i` corresponds to the feature at position `i`.

---

### Step 3: `argsort` returns indices

```python
coef = logit.coef_.ravel()

np.argsort(coef)
```

returns:

```python
array([3, 2, 0, 1])
```

because:

```text
-2.8   (index 3)
 0.1   (index 2)
 0.5   (index 0)
 2.1   (index 1)
```

---

### Step 4: Use those indices on feature names

```python
feature_names = np.array(cv.get_feature_names_out())

feature_names[np.argsort(coef)]
```

gives:

```python
array([
    'terrible',
    'movie',
    'acting',
    'great'
])
```

Now you've converted:

```python
[3, 2, 0, 1]
```

into the actual words.

---

### What's happening in your code?

When you do:

```python
coef = logit.coef_.ravel()

negative_coeff = np.argsort(coef)[:25]
```

`negative_coeff` contains the indices of the 25 smallest coefficients.

Something like:

```python
array([339, 82, 451, ...])
```

Then:

```python
feature_names = np.array(cv.get_feature_names_out())

feature_names[negative_coeff]
```

means:

```python
feature_names[339]
feature_names[82]
feature_names[451]
...
```

and NumPy returns all those words at once.

So if:

```python
coef[339] = -0.110
```

and

```python
feature_names[339] == 'awful'
```

then the model learned that `"awful"` is one of the strongest negative indicators.

---

### Why can we trust the alignment?

Because the vectorizer creates the columns of `X` in a fixed order:

```python
X[:, 0] -> feature_names[0]
X[:, 1] -> feature_names[1]
X[:, 2] -> feature_names[2]
...
```

and logistic regression learns:

```python
coef[0] -> weight for X[:, 0]
coef[1] -> weight for X[:, 1]
coef[2] -> weight for X[:, 2]
...
```

So:

```python
feature_names[i]
```

and

```python
coef[i]
```

always refer to the same feature.

A useful check is:

```python
for i in range(10):
    print(i, feature_names[i], coef[i])
```

This makes the relationship between column index, word, and learned weight very concrete.


# Feature names same the exact order as the weights

Exactly.

The **feature names and weights share the same index positions**.

If:

```python
feature_names = cv.get_feature_names_out()
coef = logit.coef_.ravel()
```

then:

```python
feature_names[0]  <-->  coef[0]
feature_names[1]  <-->  coef[1]
feature_names[2]  <-->  coef[2]
...
```

They are aligned because:

1. `CountVectorizer` (or `TfidfVectorizer`) creates the columns of `X`.
2. Each column corresponds to one feature name.
3. Logistic regression learns one coefficient for each column.
4. The coefficient is stored at the same index as the column/feature.

For example:

```python
feature_names
```

might be

```python
array(['acting', 'awful', 'great', 'movie'])
```

and

```python
coef
```

might be

```python
array([0.3, -2.1, 1.8, 0.1])
```

Then:

| Index | Feature | Weight |
| ----- | ------- | ------ |
| 0     | acting  | 0.3    |
| 1     | awful   | -2.1   |
| 2     | great   | 1.8    |
| 3     | movie   | 0.1    |

So:

```python
feature_names[np.argmin(coef)]
```

would return:

```python
'awful'
```

because `awful` has the most negative coefficient.

And:

```python
feature_names[np.argmax(coef)]
```

would return:

```python
'great'
```

because `great` has the most positive coefficient.

A nice way to see this directly is:

```python
for word, weight in zip(feature_names, coef):
    print(word, weight)
```

This prints each feature alongside its learned weight, making the alignment obvious.

One subtle point: the feature names are **not sorted by weight**. They are stored in the vectorizer's vocabulary order. `argsort(coef)` gives you the indices needed to reorder them by weight. That's why:

```python
feature_names[np.argsort(coef)]
```

returns the features ordered from most negative coefficient to most positive coefficient.


-----

# How argsort returns the best and the worst review words

Exactly.

Assume:

```python
coef = logit.coef_[0]
```

might look like:

```python
coef = np.array([
    -2.8,   # bad
     0.1,   # movie
     2.3,   # good
    -1.5,   # boring
     1.8    # amazing
])
```

### What `np.argsort(coef)` does

It returns the indices that would sort the coefficients from smallest to largest:

```python
np.argsort(coef)
```

returns:

```python
array([0, 3, 1, 4, 2])
```

because:

```text
index 0 -> -2.8
index 3 -> -1.5
index 1 ->  0.1
index 4 ->  1.8
index 2 ->  2.3
```

---

### Negative coefficients

```python
negative_coefficients = np.argsort(coef)[:n_top_features]
```

If:

```python
n_top_features = 2
```

then:

```python
negative_coefficients
```

becomes:

```python
array([0, 3])
```

These are the indices of the **most negative weights**:

```text
bad    -> -2.8
boring -> -1.5
```

These words push predictions toward class **0**.

---

### Positive coefficients

```python
positive_coefficients = np.argsort(coef)[-n_top_features:]
```

With:

```python
n_top_features = 2
```

you get:

```python
array([4, 2])
```

corresponding to:

```text
amazing -> 1.8
good    -> 2.3
```

These are the **largest positive weights**.

---

### Small subtlety

Notice:

```python
np.argsort(coef)[-n_top_features:]
```

returns them in ascending order among the selected items:

```python
[4, 2]
```

which corresponds to:

```text
1.8
2.3
```

If you want the strongest positive feature first, you often reverse them:

```python
positive_coefficients = np.argsort(coef)[-n_top_features:][::-1]
```

giving:

```python
[2, 4]
```

so:

```text
good    -> 2.3
amazing -> 1.8
```

---

### Mapping back to words

Usually you'll have:

```python
feature_names = vectorizer.get_feature_names_out()
```

Then:

```python
for idx in positive_coefficients:
    print(feature_names[idx], coef[idx])
```

might print:

```text
good 2.3
amazing 1.8
```

and:

```python
for idx in negative_coefficients:
    print(feature_names[idx], coef[idx])
```

might print:

```text
bad -2.8
boring -1.5
```

So yes, those two lines are selecting the features with the **largest positive coefficients** and **largest negative coefficients**, which are typically interpreted as the words most strongly associated with class `1` and class `0`, respectively.


# is it sorting the weights first then creating indices?

Not quite. This is a very common misunderstanding about `argsort()`.

`np.argsort()` **does not sort the actual array and then create new indices**.

Instead, it directly returns:

> "What indices would put this array in sorted order?"

For example:

```python
coef = np.array([10, -5, 7, 2])
```

Indices are:

```text
index:  0   1   2   3
value: 10  -5   7   2
```

Now:

```python
np.argsort(coef)
```

returns:

```python
array([1, 3, 2, 0])
```

because:

```text
coef[1] = -5
coef[3] =  2
coef[2] =  7
coef[0] = 10
```

which is the sorted order:

```text
-5 < 2 < 7 < 10
```

You can think of it as:

```python
sorted_indices = np.argsort(coef)
```

and then:

```python
coef[sorted_indices]
```

gives:

```python
array([-5, 2, 7, 10])
```

Notice:

* `coef` itself is unchanged.
* `argsort()` returns the indices that would sort it.

---

In your code:

```python
positive_coefficients = np.argsort(coef)[-n_top_features:]
```

Suppose:

```python
coef = np.array([-3.1, 0.5, 2.8, -1.2, 4.3])
```

Then:

```python
np.argsort(coef)
```

returns:

```python
array([0, 3, 1, 2, 4])
```

meaning:

```text
-3.1  (index 0)
-1.2  (index 3)
 0.5  (index 1)
 2.8  (index 2)
 4.3  (index 4)
```

Now:

```python
np.argsort(coef)[-2:]
```

takes the last two indices:

```python
array([2, 4])
```

which correspond to the two largest coefficients:

```text
index 2 -> 2.8
index 4 -> 4.3
```

So the flow is:

```text
coefficients
      ↓
argsort()
      ↓
indices ordered by coefficient value
      ↓
take first N  → most negative
take last N   → most positive
```

The actual coefficient array is never reordered unless you explicitly do something like:

```python
coef_sorted = np.sort(coef)
```

`sort()` returns sorted values, while `argsort()` returns the indices that would produce that sorting.
